mozilla-it/deploy-actions

deploy/action.yaml
Including the [--dependency-update](https://helm.sh/docs/helm/helm_upgrade/) flag to add support for sub-charts.
=> Add dependency-update flag to include subchart updates

deploy/action.yaml
Add support for a helm `--timeout` flag for cases where default 600 seconds is not enough.
=> feat(deploy): add helm timeout parameter

deploy/action.yaml
[Helm timeout value is a Go duration](https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback). Added missing `s` to default value
=> fix(deploy): add missing helm timeout default value unit

deploy/action.yaml
Add support to override image tag in a custom path for usages where image is defined elsewhere then the default location used in the bootstrapping process.
=> feat(deploy): add support for custom image tag value path

deployment-status/Dockerfile, deployment-status/README.md, deployment-status/action.yml, deployment-status/app/entrypoint.sh, deployment-status/app/main.py, deployment-status/app/requirements.txt
This is a GitHub action replacement of a script we have been running during application deployments in our legacy environments. 
It is intended to create `GitHub deployments` on the application repository. Ex. https://github.com/mozilla/fxa/deployments/staging
Various teams have been using `GitHub deployments` on the application repos to track deployment frequency and status. `GitHub deployments` will also be required on application repositories if we roll out the four keys dashboard more broadly.
=> Initial commit of deployment-status github action

docker-push/action.yml
This action allows pushing an image to Google Artifact Registry using workload identity federation as authentication.
A successful test run using this action: https://github.com/mozilla-sre-deploy/smarnach-eliot-test/actions/runs/6796281083/job/18476076392
For what it's worth, if the project id is stored in a GitHub Actions secret, this action does not leak it in the logs.
=> Add action to push Docker images to GAR.

deploy/action.yaml
The auth action now emits an error on every run indicating that v0 is no longer maintained. It still works fine, but results in steps marked as failed in the web interface, and there is no reason not to upgrade.
There are no breaking changes in the changelog, and the docker-push action already uses v1 of the auth action, which I confirmed to work. During testing of the docker-push action I also successfully used v1 of the get-gke-credentials action.
=> deploy: Upgrade Google actions to v1.

docker-push/action.yml
This change adds a `deployment_env` parameter for the `docker-push` action. If the parameter is set, the action will create a GitHub "deployment" object via the API. A GitHub deployment doesn't do anything by itself, but it triggers an event that can be sent to the event router and picked up in the deployment repository. This is useful because it allows triggering workflows in the deployment repo whenever a new image was pushed. I successfullly tested this with Eliot.
=> docker-push: Allow generating deployment event.

render-and-diff-helm/README.md, render-and-diff-helm/action.yml
Added a new reusable action to render helm charts on both base and head refs, then post the diff as a comment or comments on the associated pull request. 
There are a few changes here from what I demoed in the sandbox: 
1. Using a matrix to split chart rendering into jobs
This slows down smaller changes but significantly improves performance when multiple charts need to be rendered 
2. Splitting large diffs into multiple comments 
This is using a function adapted from the Atlantis SplitComment code to ensure we are sending comments within the limits defined by GitHub, I have also reused the summary and sep additions to string comments together. 
3. I am excluding files that do not exist in either head or base ref, this was done intentionally to avoid having 100s of comments on a pull …
=> feat: add render and diff helm action

slack/action.yaml
GitHub is deprecating Nodejs 16 for 20.
https://github.com/slackapi/slack-github-action/releases/tag/v1.25.0
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
=> fix(slack/action): Update to latest to get new node runtime

.github/workflows/diff-rendered-charts.yml
using environment variable for head_ref  to avoid command injection issues. 
See: https://securitylab.github.com/research/github-actions-untrusted-input/
=> fix(diff-rendered-charts): using environment variable for head_ref 

deployment-status/README.md, deployment-status/app/main.py
Allow GitHub app keys to be provided as pem files or environment variables. 
The documentation supports a key file being provided, but we are passing in an environment variable when using this in a GitHub action. 
I am adding a quick if statement to read in a file if the key is provided following the GitHub app format.
=> fix(deployment-status): allow GitHub app keys to be provided as pem files or environment variables

.github/workflows/validate-k8s-manifests.yml
**CHANGES:**
* Added custom schema location 
After rolling this action out more broadly we encountered a few missing CRD schemas, I have opened PRs to the public repository to add them, but we should also have a way to add custom schemas for validation. 
A full set of CRD schemas has been generated and merged into mozilla/mozcloud, this adds another schema location pointing at our own schema repository.
=> feat(validate-k8s-manifest): added custom schema location pointing at mozcloud crdSchemas

.github/workflows/diff-rendered-charts.yml, .github/workflows/validate-k8s-manifests.yml
**CHANGES:** 
* Reverting persist-credentials change 
We are using the git credentials in future steps to checkout different branches and render charts. Setting persist-credentials to true with a comment about it's use
=> fix(helmdiff,validate-k8s-manifest): enabled persist-credentials when we check out git repositories, we are using those credentials in future steps

.github/workflows/validate-k8s-manifests.yml
**CHANGES:** 
* Ensure we can support changes to multiple charts when one chart passes and another fails validation 
* Set default kubeconform-like output and append values to it as we iterate through chart validation
=> feat(validate-k8s-manifests): add support for changes to multiple charts at a time

.github/workflows/psa-checker.yml
`cut` is currently grabbing the top-level directory name rather than the chart name, causing errors like [this](https://github.com/mozilla/webservices-infra/actions/runs/16030581941/job/45229904873?pr=6352) when the names don't match.
Validated [here](https://github.com/mozilla/webservices-infra/actions/runs/16031579969/job/45233315709?pr=6356)
=> Fix psa-checker CHART_DIR parsing

.github/workflows/build-and-push.yml
Adds a reusable, "paved path" workflow for building and publishing Docker container images using the `docker-build` and `docker-push` actions found in this repo.
To test this workflow, I ran it successfully [here](https://github.com/mozilla/cicd-demos/actions/runs/16052637186/job/45298956920).
=> Add reusable workflow to build and publish Docker container images

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a basic PR template matching this current PR description, as proposed [here](https://docs.google.com/document/d/1llOEaOnEppTFbXkk76aicYpqwysFQ659BGdOFm6ISq8/edit?usp=sharing).
* SVCSE-3434
=> chore: Add simple PR template.

.github/workflows/build-and-push.yml, .github/workflows/docs/build-and-push.md
Following up on #79, in this PR, we add the `dockerfile_path` option to the `build-and-push` reusable workflow
* MZCLD-634
=> feat: add `dockerfile_path` option to build-and-push workflow

docker-push/README.md
* update image_tags yaml example in docker push action, we need to prune the newline when using it this way
* MZCLD-786
* https://github.com/mozilla/experimenter/actions/runs/16970960080/job/48107508286?pr=13277#step:6:176
=> chore(docker-push): update image_tags yaml example in docker push action, we need to prune the newline when using it this way

.github/workflows/validate-k8s-manifests.yml
The filepath returned from `find` will include the chart's containing directory
Example: https://github.com/mozilla/global-platform-admin/actions/runs/17743768851/job/50423920158?pr=4185
```
Error: open argo/k8s/argocd-bootstrap/argo/k8s/argocd-bootstrap/webservices.values.yaml: no such file or directory
```
<details><summary>Details</summary>
<p>
```
bash-5.3$ pwd
/Users/grahamalama/code/github/mozilla-it/global-platform-admin
bash-5.3$ echo $MATRIX_CHART
argo/k8s/argocd-bootstrap
bash-5.3$ find "$MATRIX_CHART" -maxdepth 1 -type f \( -name '*values*.yaml' -o -name '*values*.yml' \) ! \( -name 'values.yaml' -o -name 'values.yml' \)
argo/k8s/argocd-bootstrap/webservices.values.yaml
argo/k8s/argocd-bootstrap/sandbox.values.yaml
argo/k8s/argocd-bootstrap/notifications.values.yaml …
```
=> fix(validate-k8s): Skip `$MATRIX_CHART` prefix when passing values override files

.github/workflows/build-and-push.yml, docker-build/action.yml
* Support for docker_build_args was added to the docker-build action a few weeks ago, adding that support to the reusable build and push action as well.  
* Removing the input type from the docker-build composite action 
* MZCLD-983
=> Mzcld 983 add build args reusable action

.github/workflows/build-and-push.yml
These permissions should be inherited from the caller so it can control which permissions it needs specifically. Before this commit, `packages: write` had to be enabled even if the caller wasn't pushing the built image to GHCR.
* MZCLD-845
* closes #70 
I tested this change in https://github.com/mozilla/cicd-demos. On a [new branch](https://github.com/mozilla/cicd-demos/tree/test-permissions), I pointed the workflow at this PR's branch and manually ran it -- [once](https://github.com/mozilla/cicd-demos/actions/runs/17985272400/job/51161756987) with `packages: write` and `should_tag_ghcr: true`, and once [without](https://github.com/mozilla/cicd-demos/actions/runs/17985370843/job/51162096675). Both runs were successful.
=> feat(build-and-push): Remove permissions block from build-and-push workflow
